name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v4

    - name: Cache Fixtures
      id: cache-fixtures
      uses: actions/cache@v3
      with:
        path: data/
        key: ${{ runner.os }}-{{ hashFiles('get_test_data.sh') }}-{{ hashFiles('.gitignore') }}

    - name: Download Fixtures
      if: steps.cache-fixtures.outputs.cache-hit != 'true'
      run: ./get_test_data.sh

    - name: Set Up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Instrument code
      uses: AryazE/auto-dylin/instrument@main

    - name: Run Unit Tests
      run: pytest
    
    - name: Report results
      if: always()
      uses: AryazE/auto-dylin/report@main
